name: Bug report
description: Report a reproducible bug in Shotwell
title: "[Bug] "
labels:
  - needs-triage
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the bug
      placeholder: The export button closes the app when frame mode is enabled.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Open Shotwell
        2. Enable frame
        3. Tap Export
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: Export should complete and share sheet should appear.
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: App freezes and closes.
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Contact email (optional)
      placeholder: you@domain.com
    validations:
      required: false
